### ISSUE TITLE
Crashes with typescript

### ISSUE THREAD

**Issue by EthanSK** [dondevi/promise-abortable#1]
import getAbortController from "./controller.js";

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:722:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/ethan/codeProjects/YoutuberWordFinderBot/dist/run.js:13:26)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)

**Comment by dondevi** [comment]
Can you try require cjs file in dist?

**Comment by dondevi** [comment]
Try require "cjs" file in `dist`, like:

`const AbortablePromise = require("promise-abortable/dist/cjs.es6.js");`

**Comment by dondevi** [comment]
Fixed on 1.2.6, please update :-)

`const AbortablePromise = require("promise-abortable");`
